### Big Display
GET http://localhost:8080/label?displayId=0ABE5B6D74D4&articleText=test&articlePrice=9.99


### Small Display
GET http://localhost:8080/label?displayId=0AC0F23A70D8&articleText=test&articlePrice=1.99
